import numpy as np
from scipy import optimize

def ellipseFit(data):
    ...
    center = optimize.fmin(f, center0, disp=False)
    ...
    return ...


def sseOfEllipseFit(center, data):
    ...